server:
  port: 8081
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: cn.yihu.microboot.vo            # 定义所有操作类的别名所在包
  mapper-locations:                                     # 所有的mapper映射文件
  - classpath:mybatis/mapper/**/*.xml
spring:
  messages:
    basename: i18n/Messages,i18n/Pages
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy      # 配置MySQL的驱动程序类
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/dreamTask?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false           # 数据库连接地址
    username: root                                  # 数据库用户名
    password: Ab123456                            # 数据库连接密码
    filters: stat,wall,log4j
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数    
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
  resources:
    static-locations: file:/home/images

OSS:    
 endpoint: oss-cn-beijing.aliyuncs.com
 accessKeyId: LTAI4Fs3cRyRg8BDGxGE28jD
 accessKeySecret: rpSDKfWczgGiaXTAHfPm4vkUDGGb0F
 bucketName: yang610463.oss-cn-beijing.aliyuncs.com